name = "Lucas P. Doyle"
email = "lucas.p.doyle@gmail.com"
cellphone = "603-998-3565"
pdfLink = "http://stonelinks.github.io/resume/lucas_doyle_resume.pdf"

websiteName = "stonelinks.org/luke"
websiteAddress = "http://stonelinks.org"

addressLineOne = "737 Hyde Street Apt. 302"
addressLineTwo = "San Francisco, CA 94109"

[socialNetworks]
github = "https://github.com/Stonelinks"
twitter = "https://twitter.com/#!/Stonelinks"
linkedin = "http://www.linkedin.com/pub/lucas-doyle/25/550/169"
youtube = "https://www.youtube.com/c/LukeDoyle0"
# youtube = "http://www.youtube.com/user/RealStonelinks"
dribbble = "https://dribbble.com/Stonelinks"

gaCode = "UA-18750328-2"
